# Generated by Django 3.1.4 on 2020-12-23 19:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201223_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'small'), ('L', 'large'), ('M', 'Medium'), ('Xl', 'Xlarge')], max_length=20),
        ),
    ]
