# Generated by Django 3.1.4 on 2020-12-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201220_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image3',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Womem', 'Womem'), ('Children', 'Children'), ('Accessories', 'Accessories')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'small'), ('L', 'large'), ('M', 'Medium'), ('Xl', 'Xlarge')], max_length=20),
        ),
    ]
