# Generated by Django 3.1.4 on 2020-12-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201220_1432'),
        ('core', '0006_auto_20201220_1350'),
    ]

    operations = [
    ]
