# Generated by Django 3.1.4 on 2020-12-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201220_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Child', 'Child'), ('Men', 'Men'), ('Womem', 'Womem'), ('Accessories', 'Accessories')], max_length=20),
        ),
    ]
