# Generated by Django 3.1.4 on 2020-12-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201220_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='01.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='01.png', upload_to=''),
        ),
    ]
